"""add created_at to users

Revision ID: 314b19ee6b48
Revises: 8f6db33404fa
Create Date: 2025-08-03 16:07:10.800776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314b19ee6b48'
down_revision = '8f6db33404fa'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ### 