"""add created_at to users

Revision ID: 50758cb8fda4
Revises: 314b19ee6b48
Create Date: 2025-08-03 16:07:22.052238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50758cb8fda4'
down_revision = '314b19ee6b48'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 